### ISSUE TITLE
Can't compile on Ubuntu 14.04.2 LTS (Server)

### ISSUE THREAD

**Issue by burggraf** [rcouch/rcouch#24]
When trying to compile on Ubuntu (using make or make rel) I get:

==> ssl_verify_hostname (compile)
src/ssl_verify_hostname.erl:9: can't find include lib "ssl/src/ssl_alert.hrl"
make: *** [compile] Error 1

**Comment by burggraf** [comment]
Reinstalling the latest version of Erlang fixed it.

**Comment by benoitc** [comment]
@burggraf thanks for the feedback :) (sorry for the late answer)
