### ISSUE TITLE
Dropbox not included in rcouch

### ISSUE THREAD

**Issue by sergio91pt** [rcouch/rcouch#25]
The code is in [couch_core](https://github.com/rcouch/couch_core/commit/742846156eb5b881f88b88c6deecbef4e66ed2a0) but it is not in [apps/couch/src/couch_db.erl](https://github.com/rcouch/rcouch/blob/master/apps/couch/src/couch_db.erl) and it doesn't seem to get pulled when one does `make rel` or `make package` (both in `master` and `rcouch-1.1.0`).

Is this intended?

--

And so the example in the wiki doesn't work:
```
$ curl -XPUT admin:test@127.0.0.1:5984/testdb/_security -d'{"dropbox": true}'
{"ok":true}
$ curl -XGET 127.0.0.1:5984/testdb/test1
{"_id":"test1","_rev":"1-967a00dff5e02add41819138abb3284d"}

$ curl -XGET 127.0.0.1:5984/testdb/_security
{"dropbox":true}
$ curl -XGET 127.0.0.1:5984/_users/_all_docs
{"error":"forbidden","reason":"Only admins can access _all_docs of system databases."}

$ curl -XGET 127.0.0.1:5984/testdb/_all_docs
{"total_rows":2,"offset":0,"rows":[
{"id":"test","key":"test","value":{"rev":"1-967a00dff5e02add41819138abb3284d"}},
{"id":"test1","key":"test1","value":{"rev":"1-967a00dff5e02add41819138abb3284d"}}
]}
```

**Comment by benoitc** [comment]
You can actually replace it by the validate-on-read. A pure implementation will be done using the Hook system asap.

**Comment by benoitc** [comment]
closing since the development is superseded by [barrel](https://barrel-db.org) in benoitc/barrel#2.
