### ISSUE TITLE
Can't build on Mac OS X 10.10

### ISSUE THREAD

**Issue by appelgriebsch** [rcouch/rcouch#26]
==> rel (generate)
ERROR: generate failed while processing /Users/appelgriebsch/Downloads/rcouch-rcouch-1.1.0/rel: {'EXIT',{{badmatch,{error,"goldrush: Application version clash. Multiple directories contain version \"0.1.6\"."}},

Latest version of Erlang / Elixir installed locally.

**Comment by benoitc** [comment]
did you install the erlang version of Erlang Solutions?

**Comment by appelgriebsch** [comment]
Yes, Version 17 

On Tue Apr 14 17:19:44 2015 GMT+0200, Benoit Chesneau wrote:
> did you install the erlang version of Erlang Solutions?
> —
> Reply to this email directly or view it on GitHub.￼
>

-- 
Sent from my Jolla

**Comment by benoitc** [comment]
@appelgriebsch that's the issue then, since ESL ship its own version of goldrush it's conflict with the one embedded in an rcouch release. This will be fixed with the move to rebar3

**Comment by benoitc** [comment]
Will be fixed by #28

**Comment by benoitc** [comment]
fixed in latest master.
